version: "3"
services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    pid: host
    restart: always

  alertmanager:
    container_name: alertmanager
    build: ./alertmanager
    ports:
      - 9093:9093
    restart: always

  prometheus:
    container_name: prometheus
    build: ./prometheus
    ports:
      - 9090:9090
    restart: always

  web:
    container_name: web
    build: ./flask-redis
    ports:
      - 5000:5000
      - 8010:8010
    restart: always
